FROM jupyter/minimal-notebook:latest
RUN pip install aliyun-python-sdk-imagesearch 
RUN pip install pillow
RUN git clone https://github.com/jianhuashao/AlibabaCloud_ImageSearch_Demo_py2.git /home/jovyan/demo