apiVersion: autoscaling.alibabacloud.com/v1beta1
kind: CronHorizontalPodAutoscaler
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: cronhpa-sample
spec:
   scaleTargetRef:
      apiVersion: apps/v1beta2
      kind: Deployment
      name: cron-hpa-pod-demo
   jobs:
   - name: "scale-down"
     schedule: "30 */1 * * * *"   #it will scale-down every 30th seconds of each minute 
     targetSize: 1
   - name: "scale-up"
     schedule: "0 */1 * * * *"  #it will scale-up every first seconds of each minute 
     targetSize: 3