apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress-piggy
  namespace: pm
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: piggymetrics.returntrue.cc
    http:
      paths:
      - path: /
        backend:
          serviceName: gateway
          servicePort: 80
